### ISSUE TITLE
WSOD on clicking "pricing and plans" when connected to edge org "gsc"

### ISSUE THREAD

**Issue by arunz6161** [apigee/apigee-m10n-drupal#166] opened 2019-07-11 18:56 UTC
**Describe the bug**
Issue is specific to org "gsc". When portal is pointing to this org, trying to open "pricing and plans" results in WSOD

**To Reproduce**
1. Connect portal to gsc org ( reach out to me for creds)
2. Click on "pricing and plans" 
3. WSOD'

**Expected behavior**
No error.

**Screenshots**

**Additional context**
Error from recent logs:

Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "rate_plan" for route "entity.rate_plan.canonical" must match "[^/]++" ("novak-ccxb_15/month_at_start" given) to generate a corresponding URL. in Drupal\Core\Routing\UrlGenerator->doGenerate() (line 204 of /app/web/core/lib/Drupal/Core/Routing/UrlGenerator.php).

**Version Info**
m10n version : 8.x-1.0-rc1
edge version: 8.x-1.0

**Comment by arlina-espinoza** [comment] 2019-07-15 22:24
@arunz6161 Could you let us know if this is still happening with rc2? Thanks!

**Comment by arunz6161** [comment] 2019-07-16 05:49
@arlina-espinoza - yes, it is still happening with rc2. Happy to demo the issue if needed.

**Comment by shadcn** [comment] 2019-07-16 19:24
OK I can reproduce this bug too. I'll take a look at it.

**Comment by shadcn** [comment] 2019-07-17 11:54
@arunz6161 It looks like the issue here is with the `15/month at start` rate plan. The forward slash in the rate plan id is resulting in a fatal error.

We could implement a fix or a workaround for this in `apigee_m10n` but it seems this is also causing a bug on apigee.com.

To reproduce:

1. Login on https://login.apigee.com/login
2. Sign in with credentials for the GSC organization.
3. Go to https://enterprise.apigee.com/platform/gsc/packages
4. Click on any rate plan. You should see the rate plan detail.
5. Now click on the `15/month at start` rate plan. You will see a 404.
6. This is true for products as well. Try any product vs the `HelloWorld 15/month` product.

Can you check if this could be fixed on Apigee? 

To prevent a fatal error, I've created an issue with a PR for `apigee_edge`.

https://github.com/apigee/apigee-edge-drupal/issues/241
https://github.com/apigee/apigee-edge-drupal/pull/242

**Comment by mxr576** [comment] 2019-07-17 14:44
> @arunz6161 It looks like the issue here is with the 15/month at start rate plan. The forward slash in the rate plan id is resulting in a fatal error.

> Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "rate_plan" for route "entity.rate_plan.canonical" must match "[^/]++" ("novak-ccxb_15/month_at_start" given) to generate a corresponding URL.

Based on the above it is quite clear to me that https://github.com/apigee/apigee-edge-drupal/issues/241 and https://github.com/apigee/apigee-edge-drupal/pull/242 are not valid fixes for these issues and they are just bad workarounds that could only mitigate this problem in these particular places.
Also, these may "fixes" the `toUrl()` methods of the entity API but other parts of the entity API could also validate the entity ID just as `toUrl()` does and fails. What we'll do if other methods starts failing because the rate plan's id is not a valid entity id? We'll try-catch everything?

I would rather investigate how it is possible that a rate plan's id contains `/` character that is should not, because as far as I know it should not accept by the Apigee API. If this issue caused by a bug with a specific Apigee version then I would recommend to validate in Drupal the loaded rate plans before they gets parsed to Drupal entities and remove all rate plans that id contains an invalid string. If a rate plan had to be removed from results it should be logged with critical severity.

**Comment by shadcn** [comment] 2019-07-17 14:52
@mxr576 Yeah I agree that these should be investigated in Apigee. 

The PR was to at least fail gracefully with an exception instead of a WSOD. `toUrl()` throws these exceptions so we can avoid WSOD for situation like these.

**Comment by mxr576** [comment] 2019-07-17 14:55
Well, the WSOD should be prevented like I described otherwise you just hide issues like this and next time it will take more time to discover similar problems. Also, as I wrote in #242:
> If you check usages of toUrl() in Drupal core you do not see that it would be try-catched either.

even if it is documented that it could throw exception, it never gets catched directly anywhere because if the exception gets thrown then it is a fatal error that must be investigated. So please rather sanitize the rate plans retrieved from Apigee Edge before they get converted to Drupal entities instead.

**Comment by arunz6161** [comment] 2019-07-17 20:35
@mxr576 - thanks for your inputs and i agree that this should be fixed on the edge side ( Apigee). I will log a bug. But yes, we need to prevent WSOD and provide a better error response.

**Comment by arunz6161** [comment] 2019-07-18 17:07
From testing on the new UI - i do see that rate plans with forward slash do get displayed on the UI.

<img width="1368" alt="Screen Shot 2019-07-18 at 9 56 06 AM" src="https://user-images.githubusercontent.com/4381612/61477307-c7b5e380-a943-11e9-9613-9cae727459f8.png">

Might be worth checking what management server is returning.

**Comment by shadcn** [comment] 2019-07-18 18:03
The new UI is probably not using the ID. The rate plan component is bound to the passed object in Angular. So the click event works.

**Comment by shadcn** [comment] 2019-07-18 18:06
Here's how you can reproduce the error in the new UI. 

1. Click on edit for the `15/month at start` rate plan.
2. Toggle the end date.
3. Save.

This uses the ID in the PUT request URL and fails. You will see a 404. But it works for other rate plans.

![UE_-_Apigee_-_Monetization](https://user-images.githubusercontent.com/124599/61481031-375dba00-a9a8-11e9-94c1-50ca0eb8742e.jpg)

**Closed as completed** 2019-07-18 23:07 UTC
Labels: bug
